apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      initContainers:
      - name: clean-and-fix-permissions
        image: busybox
        command:
          - sh
          - -c
          - |
            rm -rf /var/lib/mysql/* && \
            chown -R 999:999 /var/lib/mysql
        volumeMounts:
        - name: user-db-storage
          mountPath: /var/lib/mysql

      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: user-db-secret
              key: MYSQL_DATABASE
        args:
          - "--explicit_defaults_for_timestamp"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: user-db-storage
          mountPath: /var/lib/mysql

      volumes:
      - name: user-db-storage
        persistentVolumeClaim:
          claimName: user-db-pvc

