apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order
        image: 029518226314.dkr.ecr.us-east-1.amazonaws.com/project:order-api
        ports:
        - containerPort: 5000
