apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-csi
provisioner: ebs.csi.eks.amazonaws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.ebs.csi.eks.amazonaws.com/zone
    values:
    - us-east-1c
    - us-east-1d
    - us-east-1a
    - us-east-1f
    - us-east-1b
parameters:
  type: gp2
