apiVersion: v1
kind: Service
metadata:
  name: cproduct-service
  namespace: microservices-app
spec:
  selector:
    app: product-service
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP
