apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user
        image: 753450714889.dkr.ecr.us-east-1.amazonaws.com/project:user-api
        ports:
        - containerPort: 5001

