apiVersion: batch/v1
kind: Job
metadata:
  name: user-db-migrate
  namespace: microservices-app
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: 753450714889.dkr.ecr.us-east-1.amazonaws.com/project:user-api
        command: ["sh", "-c", "flask db init && flask db migrate && flask db upgrade"]
      restartPolicy: Never


