apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product
        image: 029518226314.dkr.ecr.us-east-1.amazonaws.com/project:product-api
        ports:
        - containerPort: 5000
