apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices-app
spec:
  selector:
    app: product-service
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
