apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: microservices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: user-db-storage
          mountPath: /var/lib/mysql
        args:
          - "--explicit_defaults_for_timestamp"
        ports:
        - containerPort: 3306
      volumes:
      - name: user-db-storage
        persistentVolumeClaim:
          claimName: user-db-pvc      
      
