name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'services/user/**'
      - 'services/product/**'
      - 'services/order/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
      REPO: project
